//! The theme tables: every shipped palette, as colours and tile shape.
//!
//! GENERATED by `design/palettes/emit-rust.mjs` from the palette files
//! there; do not edit by hand. To regenerate, from `design/palettes`:
//!
//! ```sh
//! node gen-catppuccin.mjs && node gen-native.mjs && node emit-rust.mjs
//! ```
//!
//! Every colour is `0xRRGGBBAA`, the form [`gpui_kit::rgba`] takes. The
//! tables are read by [`Theme::resolve`](crate::theme::Theme::resolve) and
//! the palette functions in [`crate::palette`]; nothing here is derived at
//! run time, so what the checks in `design/palettes` passed is what is
//! drawn.

use gpui_kit::base::ThemeAppearance;

use crate::theme::{Flavour, ThemeId};

/// A colour as `0xRRGGBBAA`.
pub type Color = u32;

/// The interface tokens of one palette half.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Ui {
    /// Window chrome: the panel, the bars, the review summary.
    pub background: Color,
    /// A raised sheet: menus, dialogs, the help overlay.
    pub surface: Color,
    /// The side panel.
    pub sidebar: Color,
    /// A sunken well: the treemap canvas, scrolling lists, key caps.
    pub inset: Color,
    pub foreground: Color,
    pub secondary: Color,
    pub bright: Color,
    pub border: Color,
    pub divider: Color,
    /// The resting fill of a control.
    pub fill: Color,
    pub accent: Color,
    pub on_accent: Color,
    /// The one strong colour: selection, the main action, reclaimable
    /// totals.
    pub highlight: Color,
    pub on_highlight: Color,
    pub danger: Color,
    pub success: Color,
    pub warning: Color,
    /// The diagonal hatch over reclaimable space.
    pub hatch: Color,
    /// The outline of the tile under the pointer.
    pub hover: Color,
    /// A tile's name on its fill, and the dimmer size beside it.
    pub label: Color,
    pub label_dim: Color,
    /// A tile marked for removal: its fill, its ring, its name.
    pub marked_fill: Color,
    pub marked_outline: Color,
    pub marked_text: Color,
    /// The disk meter: the whole volume, and the part in use.
    pub meter_track: Color,
    pub meter_used: Color,
}

/// One category's colours: the legend swatch and strip, a fill per depth,
/// and the ink over those fills where the palette's label colour does not
/// read on them.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CategoryColors {
    pub accent: Color,
    pub fills: [Color; DEPTHS],
    pub text: Option<Color>,
}

/// The age ramp, newest first: a legend swatch per bucket and a fill per
/// bucket and depth.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Age {
    pub swatches: [Color; BUCKETS],
    pub fills: [[Color; DEPTHS]; BUCKETS],
}

/// Depth steps a fill distinguishes; deeper clamps to the last.
pub const DEPTHS: usize = 5;
/// Age buckets, as [`crate::palette::AGE_BUCKETS`] lists them.
pub const BUCKETS: usize = 5;

/// How a top-level tile carries its category colour.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Strip {
    /// A band along the top edge.
    Top,
    /// A band along the left edge.
    Left,
    /// A dot in the top-left corner.
    Dot,
    /// Nothing: the fill alone says it.
    #[allow(
        dead_code,
        reason = "the schema allows a theme without a strip; none shipped
                  is one"
    )]
    None,
}

/// The tile geometry of a theme, in pixels at 100% zoom.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Shape {
    pub tile_radius: u8,
    /// The gap between top-level tiles, and between deeper ones.
    pub gap_top: u8,
    pub gap_deep: u8,
    pub strip: Strip,
    /// The band's thickness, or the dot's diameter.
    pub strip_width: u8,
    /// A highlight along a tile's top edge, in hundredths of full white;
    /// zero is none.
    pub sheen: u8,
}

/// One half of a theme: everything it draws in one appearance.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Palette {
    /// The half's own name: the Catppuccin flavour, or Light and Dark.
    pub name: &'static str,
    pub ui: Ui,
    /// In the order `treemap_view::CATEGORIES` numbers them.
    pub categories: [CategoryColors; 9],
    pub age: Age,
}

/// The tile geometry `theme` draws with, in either appearance.
pub const fn shape(theme: ThemeId) -> &'static Shape {
    match theme {
        ThemeId::Catppuccin => &CATPPUCCIN_SHAPE,
        ThemeId::CatppuccinPastel => &CATPPUCCIN_PASTEL_SHAPE,
        ThemeId::CatppuccinQuiet => &CATPPUCCIN_QUIET_SHAPE,
        ThemeId::Aqua => &AQUA_SHAPE,
        ThemeId::Graphite => &GRAPHITE_SHAPE,
        ThemeId::RosePine => &ROSE_PINE_SHAPE,
    }
}

/// The palette `theme` draws in `appearance`; `flavour` picks among the
/// dark halves of a theme that has them and is ignored otherwise.
pub const fn palette(
    theme: ThemeId,
    flavour: Flavour,
    appearance: ThemeAppearance,
) -> &'static Palette {
    match (theme, flavour, appearance) {
        (ThemeId::Catppuccin, _, ThemeAppearance::Light) => &CATPPUCCIN_LIGHT,
        (ThemeId::Catppuccin, Flavour::Frappe, ThemeAppearance::Dark) => {
            &CATPPUCCIN_FRAPPE
        }
        (ThemeId::Catppuccin, Flavour::Macchiato, ThemeAppearance::Dark) => {
            &CATPPUCCIN_MACCHIATO
        }
        (ThemeId::Catppuccin, Flavour::Mocha, ThemeAppearance::Dark) => {
            &CATPPUCCIN_MOCHA
        }
        (ThemeId::CatppuccinPastel, _, ThemeAppearance::Light) => {
            &CATPPUCCIN_PASTEL_LIGHT
        }
        (ThemeId::CatppuccinPastel, Flavour::Frappe, ThemeAppearance::Dark) => {
            &CATPPUCCIN_PASTEL_FRAPPE
        }
        (
            ThemeId::CatppuccinPastel,
            Flavour::Macchiato,
            ThemeAppearance::Dark,
        ) => &CATPPUCCIN_PASTEL_MACCHIATO,
        (ThemeId::CatppuccinPastel, Flavour::Mocha, ThemeAppearance::Dark) => {
            &CATPPUCCIN_PASTEL_MOCHA
        }
        (ThemeId::CatppuccinQuiet, _, ThemeAppearance::Light) => {
            &CATPPUCCIN_QUIET_LIGHT
        }
        (ThemeId::CatppuccinQuiet, Flavour::Frappe, ThemeAppearance::Dark) => {
            &CATPPUCCIN_QUIET_FRAPPE
        }
        (
            ThemeId::CatppuccinQuiet,
            Flavour::Macchiato,
            ThemeAppearance::Dark,
        ) => &CATPPUCCIN_QUIET_MACCHIATO,
        (ThemeId::CatppuccinQuiet, Flavour::Mocha, ThemeAppearance::Dark) => {
            &CATPPUCCIN_QUIET_MOCHA
        }
        (ThemeId::Aqua, _, ThemeAppearance::Light) => &AQUA_LIGHT,
        (ThemeId::Aqua, _, ThemeAppearance::Dark) => &AQUA_DARK,
        (ThemeId::Graphite, _, ThemeAppearance::Light) => &GRAPHITE_LIGHT,
        (ThemeId::Graphite, _, ThemeAppearance::Dark) => &GRAPHITE_DARK,
        (ThemeId::RosePine, _, ThemeAppearance::Light) => &ROSE_PINE_LIGHT,
        (ThemeId::RosePine, _, ThemeAppearance::Dark) => &ROSE_PINE_DARK,
    }
}

static CATPPUCCIN_SHAPE: Shape = Shape {
    tile_radius: 4,
    gap_top: 6,
    gap_deep: 2,
    strip: Strip::Top,
    strip_width: 2,
    sheen: 0,
};

static CATPPUCCIN_LIGHT: Palette = Palette {
    name: "Latte",
    ui: Ui {
        background: 0xe6_e9_ef_ff,
        surface: 0xef_f1_f5_ff,
        sidebar: 0xef_f1_f5_ff,
        inset: 0xdc_e0_e8_ff,
        foreground: 0x4c_4f_69_ff,
        secondary: 0x5c_5f_77_ff,
        bright: 0x2c_2e_3e_ff,
        border: 0xbc_c0_cc_ff,
        divider: 0x4c_4f_69_24,
        fill: 0x4c_4f_69_0d,
        accent: 0x88_39_ef_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xf3_54_22_ff,
        on_highlight: 0x11_11_1b_ff,
        danger: 0xd2_0f_39_ff,
        success: 0x40_a0_2b_ff,
        warning: 0xdf_8e_1d_ff,
        hatch: 0x4c_4f_69_29,
        hover: 0x4c_4f_69_99,
        label: 0x4c_4f_69_ff,
        label_dim: 0x6c_6f_85_ff,
        meter_track: 0x4c_4f_69_1a,
        meter_used: 0x4c_4f_69_4d,
        marked_fill: 0xf0_cc_ce_ff,
        marked_outline: 0xd2_0f_39_ff,
        marked_text: 0xd2_0f_39_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x1e_66_f5_ff,
            fills: [
                0xd6_e2_f7_ff,
                0xcc_db_f8_ff,
                0xc0_d4_f9_ff,
                0xb5_cd_f9_ff,
                0xaa_c6_fa_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xdc_8a_78_ff,
            fills: [
                0xed_df_de_ff,
                0xec_d6_d3_ff,
                0xeb_cd_c8_ff,
                0xea_c4_bd_ff,
                0xe8_bb_b3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x40_a0_2b_ff,
            fills: [
                0xd1_e3_d3_ff,
                0xc7_de_c7_ff,
                0xbc_d9_bb_ff,
                0xb2_d4_af_ff,
                0xa7_cf_a3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x17_92_99_ff,
            fills: [
                0xd7_e5_e9_ff,
                0xcb_de_e3_ff,
                0xbf_d8_dc_ff,
                0xb3_d2_d6_ff,
                0xa7_cc_d0_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xea_76_cb_ff,
            fills: [
                0xf1_da_ed_ff,
                0xf1_d0_ea_ff,
                0xf1_c6_e6_ff,
                0xf1_bc_e3_ff,
                0xf1_b2_df_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x88_39_ef_ff,
            fills: [
                0xe3_e0_f7_ff,
                0xdd_d8_f7_ff,
                0xd8_cf_f7_ff,
                0xd2_c7_f8_ff,
                0xcc_bf_f8_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x84_8e_bd_ff,
            fills: [
                0xe0_e4_ee_ff,
                0xd8_dc_ea_ff,
                0xcf_d4_e5_ff,
                0xc6_cc_e1_ff,
                0xbe_c4_dd_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xdf_8e_1d_ff,
            fills: [
                0xed_dd_ce_ff,
                0xec_d5_bf_ff,
                0xeb_cd_af_ff,
                0xea_c5_a0_ff,
                0xe9_bd_90_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x9c_a0_b0_ff,
            fills: [
                0xe3_e5_eb_ff,
                0xdb_dd_e4_ff,
                0xd2_d5_dd_ff,
                0xcb_cd_d7_ff,
                0xc2_c5_d0_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x1e_66_f5_ff,
            0x49_7c_e2_ff,
            0x68_8b_d2_ff,
            0x83_96_c1_ff,
            0x9c_a0_b0_ff,
        ],
        fills: [
            [
                0xd6_e2_f7_ff,
                0xcc_db_f8_ff,
                0xc0_d4_f9_ff,
                0xb5_cd_f9_ff,
                0xaa_c6_fa_ff,
            ],
            [
                0xd8_e2_f4_ff,
                0xce_db_f3_ff,
                0xc3_d4_f3_ff,
                0xb9_cd_f2_ff,
                0xaf_c6_f1_ff,
            ],
            [
                0xdc_e3_f1_ff,
                0xd2_dc_ef_ff,
                0xc8_d4_ed_ff,
                0xbe_cd_ea_ff,
                0xb4_c6_e8_ff,
            ],
            [
                0xe0_e4_ee_ff,
                0xd6_dd_ea_ff,
                0xcd_d5_e6_ff,
                0xc4_cd_e1_ff,
                0xba_c5_dd_ff,
            ],
            [
                0xe3_e5_eb_ff,
                0xdb_dd_e4_ff,
                0xd2_d5_dd_ff,
                0xcb_cd_d7_ff,
                0xc2_c5_d0_ff,
            ],
        ],
    },
};

static CATPPUCCIN_FRAPPE: Palette = Palette {
    name: "Frapp\u{e9}",
    ui: Ui {
        background: 0x29_2c_3c_ff,
        surface: 0x30_34_46_ff,
        sidebar: 0x30_34_46_ff,
        inset: 0x23_26_34_ff,
        foreground: 0xc6_d0_f5_ff,
        secondary: 0xa5_ad_ce_ff,
        bright: 0xe2_e7_fa_ff,
        border: 0x51_57_6d_ff,
        divider: 0xc6_d0_f5_1f,
        fill: 0xc6_d0_f5_0f,
        accent: 0xca_9e_e6_ff,
        on_accent: 0x23_26_34_ff,
        highlight: 0xed_99_79_ff,
        on_highlight: 0x23_26_34_ff,
        danger: 0xe7_82_84_ff,
        success: 0xa6_d1_89_ff,
        warning: 0xe5_c8_90_ff,
        hatch: 0xc6_d0_f5_24,
        hover: 0xc6_d0_f5_99,
        label: 0xc6_d0_f5_ff,
        label_dim: 0xa5_ad_ce_ff,
        meter_track: 0xc6_d0_f5_1a,
        meter_used: 0xc6_d0_f5_4d,
        marked_fill: 0x5d_43_4d_ff,
        marked_outline: 0xe7_82_84_ff,
        marked_text: 0xe7_82_84_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x8c_aa_ee_ff,
            fills: [
                0x37_3e_56_ff,
                0x3c_44_5f_ff,
                0x41_4b_67_ff,
                0x46_51_70_ff,
                0x4b_58_7a_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf2_d5_cf_ff,
            fills: [
                0x3f_3e_4a_ff,
                0x46_44_50_ff,
                0x4d_4a_55_ff,
                0x54_50_5b_ff,
                0x5c_57_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa6_d1_89_ff,
            fills: [
                0x37_41_43_ff,
                0x3c_48_47_ff,
                0x42_4f_4b_ff,
                0x47_56_4f_ff,
                0x4d_5d_53_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x81_c8_be_ff,
            fills: [
                0x34_41_4c_ff,
                0x38_48_52_ff,
                0x3c_4f_58_ff,
                0x40_56_5e_ff,
                0x44_5d_64_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf4_b8_e4_ff,
            fills: [
                0x43_3d_4f_ff,
                0x4b_42_56_ff,
                0x52_48_5d_ff,
                0x5b_4e_64_ff,
                0x63_54_6b_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xca_9e_e6_ff,
            fills: [
                0x43_3d_56_ff,
                0x4a_43_5e_ff,
                0x52_48_66_ff,
                0x59_4e_6e_ff,
                0x61_53_77_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x88_90_ae_ff,
            fills: [
                0x3a_3e_50_ff,
                0x40_44_57_ff,
                0x46_4b_5e_ff,
                0x4c_51_66_ff,
                0x52_58_6d_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xe5_c8_90_ff,
            fills: [
                0x3e_3d_43_ff,
                0x45_43_47_ff,
                0x4c_49_4b_ff,
                0x54_50_4f_ff,
                0x5c_57_53_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x73_79_94_ff,
            fills: [
                0x36_3a_4b_ff,
                0x3c_40_52_ff,
                0x42_46_59_ff,
                0x48_4d_61_ff,
                0x4f_53_69_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x8c_aa_ee_ff,
            0x85_9b_d2_ff,
            0x7e_8f_bc_ff,
            0x79_84_a7_ff,
            0x73_79_94_ff,
        ],
        fills: [
            [
                0x37_3e_56_ff,
                0x3c_44_5f_ff,
                0x41_4b_67_ff,
                0x46_51_70_ff,
                0x4b_58_7a_ff,
            ],
            [
                0x37_3d_53_ff,
                0x3c_43_5c_ff,
                0x41_4a_64_ff,
                0x47_50_6d_ff,
                0x4c_57_76_ff,
            ],
            [
                0x38_3e_52_ff,
                0x3d_44_5b_ff,
                0x43_4b_63_ff,
                0x48_51_6c_ff,
                0x4e_58_74_ff,
            ],
            [
                0x38_3d_50_ff,
                0x3e_43_58_ff,
                0x44_4a_60_ff,
                0x4a_50_68_ff,
                0x50_57_70_ff,
            ],
            [
                0x36_3a_4b_ff,
                0x3c_40_52_ff,
                0x42_46_59_ff,
                0x48_4d_61_ff,
                0x4f_53_69_ff,
            ],
        ],
    },
};

static CATPPUCCIN_MACCHIATO: Palette = Palette {
    name: "Macchiato",
    ui: Ui {
        background: 0x1e_20_30_ff,
        surface: 0x24_27_3a_ff,
        sidebar: 0x24_27_3a_ff,
        inset: 0x18_19_26_ff,
        foreground: 0xca_d3_f5_ff,
        secondary: 0xa5_ad_cb_ff,
        bright: 0xe4_e9_fa_ff,
        border: 0x49_4d_64_ff,
        divider: 0xca_d3_f5_1f,
        fill: 0xca_d3_f5_0f,
        accent: 0xc6_a0_f6_ff,
        on_accent: 0x18_19_26_ff,
        highlight: 0xf3_a2_84_ff,
        on_highlight: 0x18_19_26_ff,
        danger: 0xed_87_96_ff,
        success: 0xa6_da_95_ff,
        warning: 0xee_d4_9f_ff,
        hatch: 0xca_d3_f5_24,
        hover: 0xca_d3_f5_99,
        label: 0xca_d3_f5_ff,
        label_dim: 0xa5_ad_cb_ff,
        meter_track: 0xca_d3_f5_1a,
        meter_used: 0xca_d3_f5_4d,
        marked_fill: 0x55_3a_48_ff,
        marked_outline: 0xed_87_96_ff,
        marked_text: 0xed_87_96_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x8a_ad_f4_ff,
            fills: [
                0x33_3b_55_ff,
                0x38_41_5e_ff,
                0x3d_48_67_ff,
                0x42_4e_70_ff,
                0x47_55_79_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf6_e2_de_ff,
            fills: [
                0x41_3f_4a_ff,
                0x48_45_4f_ff,
                0x4f_4b_55_ff,
                0x56_52_5b_ff,
                0x5e_59_62_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa6_da_95_ff,
            fills: [
                0x38_44_42_ff,
                0x3c_4b_46_ff,
                0x42_52_4a_ff,
                0x47_59_4e_ff,
                0x4c_60_52_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x8a_d4_cb_ff,
            fills: [
                0x32_42_4b_ff,
                0x37_49_51_ff,
                0x3b_50_58_ff,
                0x3f_57_5e_ff,
                0x43_5e_64_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf5_bd_e6_ff,
            fills: [
                0x48_3d_51_ff,
                0x4f_43_57_ff,
                0x57_49_5e_ff,
                0x60_4f_66_ff,
                0x68_55_6d_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xc6_a0_f6_ff,
            fills: [
                0x40_38_56_ff,
                0x47_3e_5e_ff,
                0x4f_44_67_ff,
                0x56_4a_71_ff,
                0x5e_50_7a_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x85_8c_aa_ff,
            fills: [
                0x31_34_45_ff,
                0x37_3a_4c_ff,
                0x3d_40_53_ff,
                0x43_46_5a_ff,
                0x49_4d_62_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xee_d4_9f_ff,
            fills: [
                0x42_3f_41_ff,
                0x49_45_45_ff,
                0x51_4c_4a_ff,
                0x59_53_4f_ff,
                0x61_5a_53_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x6e_73_8d_ff,
            fills: [
                0x2c_2e_3f_ff,
                0x32_34_45_ff,
                0x38_3a_4c_ff,
                0x3e_40_53_ff,
                0x44_47_5a_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x8a_ad_f4_ff,
            0x82_9b_d4_ff,
            0x7b_8d_ba_ff,
            0x74_80_a3_ff,
            0x6e_73_8d_ff,
        ],
        fills: [
            [
                0x33_3b_55_ff,
                0x38_41_5e_ff,
                0x3d_48_67_ff,
                0x42_4e_70_ff,
                0x47_55_79_ff,
            ],
            [
                0x31_37_4e_ff,
                0x36_3d_57_ff,
                0x3b_44_5f_ff,
                0x41_4b_68_ff,
                0x46_51_71_ff,
            ],
            [
                0x2f_34_49_ff,
                0x35_3a_50_ff,
                0x3a_40_58_ff,
                0x3f_47_60_ff,
                0x45_4d_68_ff,
            ],
            [
                0x2e_31_44_ff,
                0x33_37_4b_ff,
                0x39_3e_53_ff,
                0x3f_44_5b_ff,
                0x45_4b_63_ff,
            ],
            [
                0x2c_2e_3f_ff,
                0x32_34_45_ff,
                0x38_3a_4c_ff,
                0x3e_40_53_ff,
                0x44_47_5a_ff,
            ],
        ],
    },
};

static CATPPUCCIN_MOCHA: Palette = Palette {
    name: "Mocha",
    ui: Ui {
        background: 0x18_18_25_ff,
        surface: 0x1e_1e_2e_ff,
        sidebar: 0x1e_1e_2e_ff,
        inset: 0x11_11_1b_ff,
        foreground: 0xcd_d6_f4_ff,
        secondary: 0xa6_ad_c8_ff,
        bright: 0xe6_ea_fa_ff,
        border: 0x45_47_5a_ff,
        divider: 0xcd_d6_f4_1f,
        fill: 0xcd_d6_f4_0f,
        accent: 0xcb_a6_f7_ff,
        on_accent: 0x11_11_1b_ff,
        highlight: 0xf9_ab_8f_ff,
        on_highlight: 0x11_11_1b_ff,
        danger: 0xf3_8b_a8_ff,
        success: 0xa6_e3_a1_ff,
        warning: 0xf9_e2_af_ff,
        hatch: 0xcd_d6_f4_24,
        hover: 0xcd_d6_f4_99,
        label: 0xcd_d6_f4_ff,
        label_dim: 0xa6_ad_c8_ff,
        meter_track: 0xcd_d6_f4_1a,
        meter_used: 0xcd_d6_f4_4d,
        marked_fill: 0x51_35_44_ff,
        marked_outline: 0xf3_8b_a8_ff,
        marked_text: 0xf3_8b_a8_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x89_b4_fa_ff,
            fills: [
                0x2d_36_4d_ff,
                0x32_3d_56_ff,
                0x37_43_5f_ff,
                0x3c_4a_69_ff,
                0x41_51_73_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xfb_f3_f1_ff,
            fills: [
                0x42_41_4a_ff,
                0x49_47_50_ff,
                0x4f_4e_56_ff,
                0x57_55_5d_ff,
                0x5e_5c_63_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa6_e3_a1_ff,
            fills: [
                0x33_40_3b_ff,
                0x38_47_40_ff,
                0x3d_4e_45_ff,
                0x42_55_49_ff,
                0x47_5c_4e_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x8f_de_d9_ff,
            fills: [
                0x2f_3f_46_ff,
                0x33_46_4d_ff,
                0x38_4d_54_ff,
                0x3c_54_5a_ff,
                0x40_5b_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf5_c2_e7_ff,
            fills: [
                0x43_39_49_ff,
                0x4b_3f_50_ff,
                0x54_45_58_ff,
                0x5b_4b_5f_ff,
                0x63_51_65_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xcb_a6_f7_ff,
            fills: [
                0x3b_33_4c_ff,
                0x42_38_55_ff,
                0x49_3e_5d_ff,
                0x50_44_66_ff,
                0x57_4a_6e_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x84_8a_a5_ff,
            fills: [
                0x2b_2d_3b_ff,
                0x31_33_42_ff,
                0x37_39_49_ff,
                0x3d_3f_50_ff,
                0x43_45_57_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf9_e2_af_ff,
            fills: [
                0x44_40_3f_ff,
                0x4b_47_43_ff,
                0x52_4d_48_ff,
                0x5a_54_4d_ff,
                0x62_5b_52_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x6c_70_86_ff,
            fills: [
                0x26_27_34_ff,
                0x2b_2d_3a_ff,
                0x31_33_41_ff,
                0x37_39_48_ff,
                0x3d_3f_4f_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x89_b4_fa_ff,
            0x81_9f_d6_ff,
            0x7a_8e_b9_ff,
            0x73_7f_9f_ff,
            0x6c_70_86_ff,
        ],
        fills: [
            [
                0x2d_36_4d_ff,
                0x32_3d_56_ff,
                0x37_43_5f_ff,
                0x3c_4a_69_ff,
                0x41_51_73_ff,
            ],
            [
                0x2b_31_45_ff,
                0x30_37_4d_ff,
                0x35_3d_55_ff,
                0x3a_44_5e_ff,
                0x3f_4b_67_ff,
            ],
            [
                0x29_2e_3f_ff,
                0x2e_34_47_ff,
                0x34_3a_4f_ff,
                0x39_40_57_ff,
                0x3f_47_5f_ff,
            ],
            [
                0x28_2a_3a_ff,
                0x2d_30_41_ff,
                0x32_36_48_ff,
                0x38_3c_4f_ff,
                0x3d_42_57_ff,
            ],
            [
                0x26_27_34_ff,
                0x2b_2d_3a_ff,
                0x31_33_41_ff,
                0x37_39_48_ff,
                0x3d_3f_4f_ff,
            ],
        ],
    },
};

static CATPPUCCIN_PASTEL_SHAPE: Shape = Shape {
    tile_radius: 5,
    gap_top: 8,
    gap_deep: 3,
    strip: Strip::Dot,
    strip_width: 6,
    sheen: 4,
};

static CATPPUCCIN_PASTEL_LIGHT: Palette = Palette {
    name: "Latte",
    ui: Ui {
        background: 0xe6_e9_ef_ff,
        surface: 0xef_f1_f5_ff,
        sidebar: 0xef_f1_f5_ff,
        inset: 0xdc_e0_e8_ff,
        foreground: 0x4c_4f_69_ff,
        secondary: 0x5c_5f_77_ff,
        bright: 0x2c_2e_3e_ff,
        border: 0xbc_c0_cc_ff,
        divider: 0x4c_4f_69_24,
        fill: 0x4c_4f_69_0d,
        accent: 0xab_54_94_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xf3_54_22_ff,
        on_highlight: 0x11_11_1b_ff,
        danger: 0xd2_0f_39_ff,
        success: 0x40_a0_2b_ff,
        warning: 0xdf_8e_1d_ff,
        hatch: 0x4c_4f_69_29,
        hover: 0x4c_4f_69_b3,
        label: 0x4c_4f_69_ff,
        label_dim: 0x6c_6f_85_ff,
        meter_track: 0x4c_4f_69_1a,
        meter_used: 0x4c_4f_69_4d,
        marked_fill: 0xf0_cc_ce_ff,
        marked_outline: 0xd2_0f_39_ff,
        marked_text: 0xd2_0f_39_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x1e_66_f5_ff,
            fills: [
                0xd6_e2_f7_ff,
                0xcc_db_f8_ff,
                0xc0_d4_f9_ff,
                0xb5_cd_f9_ff,
                0xaa_c6_fa_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xdc_8a_78_ff,
            fills: [
                0xed_df_de_ff,
                0xec_d6_d3_ff,
                0xeb_cd_c8_ff,
                0xea_c4_bd_ff,
                0xe8_bb_b3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x40_a0_2b_ff,
            fills: [
                0xd1_e3_d3_ff,
                0xc7_de_c7_ff,
                0xbc_d9_bb_ff,
                0xb2_d4_af_ff,
                0xa7_cf_a3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x17_92_99_ff,
            fills: [
                0xd7_e5_e9_ff,
                0xcb_de_e3_ff,
                0xbf_d8_dc_ff,
                0xb3_d2_d6_ff,
                0xa7_cc_d0_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xea_76_cb_ff,
            fills: [
                0xf1_da_ed_ff,
                0xf1_d0_ea_ff,
                0xf1_c6_e6_ff,
                0xf1_bc_e3_ff,
                0xf1_b2_df_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x88_39_ef_ff,
            fills: [
                0xe3_e0_f7_ff,
                0xdd_d8_f7_ff,
                0xd8_cf_f7_ff,
                0xd2_c7_f8_ff,
                0xcc_bf_f8_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x84_8e_bd_ff,
            fills: [
                0xe0_e4_ee_ff,
                0xd8_dc_ea_ff,
                0xcf_d4_e5_ff,
                0xc6_cc_e1_ff,
                0xbe_c4_dd_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xdf_8e_1d_ff,
            fills: [
                0xed_dd_ce_ff,
                0xec_d5_bf_ff,
                0xeb_cd_af_ff,
                0xea_c5_a0_ff,
                0xe9_bd_90_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x9c_a0_b0_ff,
            fills: [
                0xe3_e5_eb_ff,
                0xdb_dd_e4_ff,
                0xd2_d5_dd_ff,
                0xcb_cd_d7_ff,
                0xc2_c5_d0_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x20_9f_b5_ff,
            0x57_a0_b4_ff,
            0x73_a0_b2_ff,
            0x89_a0_b1_ff,
            0x9c_a0_b0_ff,
        ],
        fills: [
            [
                0xd2_e4_ea_ff,
                0xc6_de_e6_ff,
                0xb9_d8_e2_ff,
                0xad_d2_dd_ff,
                0x9f_cc_d8_ff,
            ],
            [
                0xd9_e5_eb_ff,
                0xcd_de_e6_ff,
                0xc1_d8_e1_ff,
                0xb5_d1_dc_ff,
                0xa9_cb_d6_ff,
            ],
            [
                0xdc_e5_eb_ff,
                0xd2_de_e5_ff,
                0xc8_d7_e0_ff,
                0xbd_d0_da_ff,
                0xb2_c9_d4_ff,
            ],
            [
                0xdf_e5_eb_ff,
                0xd6_dd_e5_ff,
                0xcd_d6_de_ff,
                0xc3_ce_d8_ff,
                0xba_c7_d2_ff,
            ],
            [
                0xe3_e5_eb_ff,
                0xdb_dd_e4_ff,
                0xd2_d5_dd_ff,
                0xcb_cd_d7_ff,
                0xc2_c5_d0_ff,
            ],
        ],
    },
};

static CATPPUCCIN_PASTEL_FRAPPE: Palette = Palette {
    name: "Frapp\u{e9}",
    ui: Ui {
        background: 0x29_2c_3c_ff,
        surface: 0x30_34_46_ff,
        sidebar: 0x30_34_46_ff,
        inset: 0x23_26_34_ff,
        foreground: 0xc6_d0_f5_ff,
        secondary: 0xa5_ad_ce_ff,
        bright: 0xe2_e7_fa_ff,
        border: 0x51_57_6d_ff,
        divider: 0xc6_d0_f5_1f,
        fill: 0xc6_d0_f5_0f,
        accent: 0xf4_b8_e4_ff,
        on_accent: 0x23_26_34_ff,
        highlight: 0xed_99_79_ff,
        on_highlight: 0x23_26_34_ff,
        danger: 0xe7_82_84_ff,
        success: 0xa6_d1_89_ff,
        warning: 0xe5_c8_90_ff,
        hatch: 0x23_26_34_2e,
        hover: 0x23_26_34_cc,
        label: 0x23_26_34_ff,
        label_dim: 0x29_2c_3c_ff,
        meter_track: 0xc6_d0_f5_1a,
        meter_used: 0xc6_d0_f5_4d,
        marked_fill: 0xe7_82_84_ff,
        marked_outline: 0xf6_bb_ba_ff,
        marked_text: 0x23_26_34_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x8c_aa_ee_ff,
            fills: [
                0x8c_aa_ee_ff,
                0x97_b3_f0_ff,
                0xa2_bb_f2_ff,
                0xad_c3_f4_ff,
                0xb8_cb_f6_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0xf2_d5_cf_ff,
            fills: [
                0xf2_d5_cf_ff,
                0xf5_df_da_ff,
                0xf8_e9_e6_ff,
                0xfc_f3_f1_ff,
                0xff_fd_fd_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0xa6_d1_89_ff,
            fills: [
                0xa6_d1_89_ff,
                0xb1_d7_97_ff,
                0xbc_dd_a6_ff,
                0xc7_e2_b5_ff,
                0xd2_e8_c4_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0x81_c8_be_ff,
            fills: [
                0x81_c8_be_ff,
                0x91_cf_c6_ff,
                0xa1_d5_cd_ff,
                0xaf_dc_d5_ff,
                0xbe_e2_dc_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0xf4_b8_e4_ff,
            fills: [
                0xf4_b8_e4_ff,
                0xf6_c3_e8_ff,
                0xf8_ce_ec_ff,
                0xfa_d9_f1_ff,
                0xfc_e4_f5_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0xca_9e_e6_ff,
            fills: [
                0xca_9e_e6_ff,
                0xcf_a8_e9_ff,
                0xd5_b2_ec_ff,
                0xda_bc_ee_ff,
                0xe0_c6_f1_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0x88_90_ae_ff,
            fills: [
                0x88_90_ae_ff,
                0x91_98_b4_ff,
                0x99_a1_ba_ff,
                0xa2_a9_c0_ff,
                0xab_b1_c7_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0xe5_c8_90_ff,
            fills: [
                0xe5_c8_90_ff,
                0xe9_d1_a2_ff,
                0xed_d9_b3_ff,
                0xf1_e1_c4_ff,
                0xf5_ea_d4_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
        CategoryColors {
            accent: 0x94_9c_bb_ff,
            fills: [
                0x94_9c_bb_ff,
                0x9d_a4_c1_ff,
                0xa6_ad_c7_ff,
                0xb0_b6_cd_ff,
                0xb9_bf_d3_ff,
            ],
            text: Some(0x23_26_34_ff),
        },
    ],
    age: Age {
        swatches: [
            0x85_c1_dc_ff,
            0x8b_b6_d2_ff,
            0x8f_ad_ca_ff,
            0x92_a4_c2_ff,
            0x94_9c_bb_ff,
        ],
        fills: [
            [
                0x85_c1_dc_ff,
                0x94_c8_e0_ff,
                0xa2_cf_e4_ff,
                0xb0_d6_e8_ff,
                0xbe_de_ec_ff,
            ],
            [
                0x8b_b6_d2_ff,
                0x97_be_d7_ff,
                0xa4_c6_dc_ff,
                0xb1_ce_e1_ff,
                0xbd_d6_e6_ff,
            ],
            [
                0x8f_ad_ca_ff,
                0x99_b5_cf_ff,
                0xa4_bd_d4_ff,
                0xaf_c5_da_ff,
                0xba_cd_df_ff,
            ],
            [
                0x92_a4_c2_ff,
                0x9c_ac_c8_ff,
                0xa6_b5_ce_ff,
                0xb0_bd_d3_ff,
                0xba_c5_d9_ff,
            ],
            [
                0x94_9c_bb_ff,
                0x9d_a4_c1_ff,
                0xa6_ad_c7_ff,
                0xb0_b6_cd_ff,
                0xb9_bf_d3_ff,
            ],
        ],
    },
};

static CATPPUCCIN_PASTEL_MACCHIATO: Palette = Palette {
    name: "Macchiato",
    ui: Ui {
        background: 0x1e_20_30_ff,
        surface: 0x24_27_3a_ff,
        sidebar: 0x24_27_3a_ff,
        inset: 0x18_19_26_ff,
        foreground: 0xca_d3_f5_ff,
        secondary: 0xa5_ad_cb_ff,
        bright: 0xe4_e9_fa_ff,
        border: 0x49_4d_64_ff,
        divider: 0xca_d3_f5_1f,
        fill: 0xca_d3_f5_0f,
        accent: 0xf5_bd_e6_ff,
        on_accent: 0x18_19_26_ff,
        highlight: 0xf3_a2_84_ff,
        on_highlight: 0x18_19_26_ff,
        danger: 0xed_87_96_ff,
        success: 0xa6_da_95_ff,
        warning: 0xee_d4_9f_ff,
        hatch: 0x18_19_26_2e,
        hover: 0x18_19_26_cc,
        label: 0x18_19_26_ff,
        label_dim: 0x1e_20_30_ff,
        meter_track: 0xca_d3_f5_1a,
        meter_used: 0xca_d3_f5_4d,
        marked_fill: 0xed_87_96_ff,
        marked_outline: 0xf9_be_c4_ff,
        marked_text: 0x18_19_26_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x8a_ad_f4_ff,
            fills: [
                0x8a_ad_f4_ff,
                0x95_b5_f6_ff,
                0xa0_bd_f7_ff,
                0xab_c5_f8_ff,
                0xb6_cd_fa_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0xf6_e2_de_ff,
            fills: [
                0xe9_d7_d4_ff,
                0xee_e1_de_ff,
                0xf4_eb_e9_ff,
                0xf9_f5_f4_ff,
                0xff_ff_ff_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0xa6_da_95_ff,
            fills: [
                0xa6_da_95_ff,
                0xb2_df_a4_ff,
                0xbe_e4_b2_ff,
                0xca_e9_c0_ff,
                0xd6_ee_ce_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0x8a_d4_cb_ff,
            fills: [
                0x8a_d4_cb_ff,
                0x9b_da_d2_ff,
                0xab_e0_d9_ff,
                0xbb_e6_e0_ff,
                0xcc_ec_e7_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0xf5_bd_e6_ff,
            fills: [
                0xf5_bd_e6_ff,
                0xf7_c8_ea_ff,
                0xf9_d3_ee_ff,
                0xfb_de_f3_ff,
                0xfc_e9_f7_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0xc6_a0_f6_ff,
            fills: [
                0xc6_a0_f6_ff,
                0xcc_aa_f7_ff,
                0xd1_b4_f9_ff,
                0xd7_be_fa_ff,
                0xdd_c8_fb_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0x85_8c_aa_ff,
            fills: [
                0x85_8c_aa_ff,
                0x8e_94_b0_ff,
                0x96_9d_b7_ff,
                0x9f_a5_bd_ff,
                0xa9_ae_c4_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0xee_d4_9f_ff,
            fills: [
                0xee_d4_9f_ff,
                0xf1_dc_b2_ff,
                0xf5_e4_c4_ff,
                0xf8_ec_d6_ff,
                0xfb_f5_e8_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
        CategoryColors {
            accent: 0x93_9a_b7_ff,
            fills: [
                0x93_9a_b7_ff,
                0x9c_a2_bd_ff,
                0xa5_ab_c3_ff,
                0xae_b4_ca_ff,
                0xb8_bd_d0_ff,
            ],
            text: Some(0x18_19_26_ff),
        },
    ],
    age: Age {
        swatches: [
            0x7d_c4_e4_ff,
            0x86_b7_d6_ff,
            0x8b_ad_cb_ff,
            0x90_a3_c1_ff,
            0x93_9a_b7_ff,
        ],
        fills: [
            [
                0x7d_c4_e4_ff,
                0x8c_cb_e7_ff,
                0x9d_d2_eb_ff,
                0xac_d9_ee_ff,
                0xbb_e0_f1_ff,
            ],
            [
                0x86_b7_d6_ff,
                0x93_bf_da_ff,
                0xa1_c7_df_ff,
                0xae_cf_e4_ff,
                0xbb_d7_e8_ff,
            ],
            [
                0x8b_ad_cb_ff,
                0x96_b5_d0_ff,
                0xa1_bd_d5_ff,
                0xad_c5_db_ff,
                0xb8_cd_df_ff,
            ],
            [
                0x90_a3_c1_ff,
                0x9a_ab_c7_ff,
                0xa4_b4_cc_ff,
                0xae_bc_d2_ff,
                0xb8_c4_d8_ff,
            ],
            [
                0x93_9a_b7_ff,
                0x9c_a2_bd_ff,
                0xa5_ab_c3_ff,
                0xae_b4_ca_ff,
                0xb8_bd_d0_ff,
            ],
        ],
    },
};

static CATPPUCCIN_PASTEL_MOCHA: Palette = Palette {
    name: "Mocha",
    ui: Ui {
        background: 0x18_18_25_ff,
        surface: 0x1e_1e_2e_ff,
        sidebar: 0x1e_1e_2e_ff,
        inset: 0x11_11_1b_ff,
        foreground: 0xcd_d6_f4_ff,
        secondary: 0xa6_ad_c8_ff,
        bright: 0xe6_ea_fa_ff,
        border: 0x45_47_5a_ff,
        divider: 0xcd_d6_f4_1f,
        fill: 0xcd_d6_f4_0f,
        accent: 0xf5_c2_e7_ff,
        on_accent: 0x11_11_1b_ff,
        highlight: 0xf9_ab_8f_ff,
        on_highlight: 0x11_11_1b_ff,
        danger: 0xf3_8b_a8_ff,
        success: 0xa6_e3_a1_ff,
        warning: 0xf9_e2_af_ff,
        hatch: 0x11_11_1b_2e,
        hover: 0x11_11_1b_cc,
        label: 0x11_11_1b_ff,
        label_dim: 0x18_18_25_ff,
        meter_track: 0xcd_d6_f4_1a,
        meter_used: 0xcd_d6_f4_4d,
        marked_fill: 0xf3_8b_a8_ff,
        marked_outline: 0xfc_c0_ce_ff,
        marked_text: 0x11_11_1b_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x89_b4_fa_ff,
            fills: [
                0x89_b4_fa_ff,
                0x95_bc_fb_ff,
                0xa1_c4_fc_ff,
                0xad_cc_fd_ff,
                0xb9_d4_fe_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0xfb_f3_f1_ff,
            fills: [
                0xe0_d9_d9_ff,
                0xe8_e2_e2_ff,
                0xef_ec_ec_ff,
                0xf7_f5_f5_ff,
                0xff_fe_fe_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0xa6_e3_a1_ff,
            fills: [
                0xa6_e3_a1_ff,
                0xb4_e7_af_ff,
                0xc1_ec_bd_ff,
                0xce_f0_cb_ff,
                0xdb_f4_d9_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0x8f_de_d9_ff,
            fills: [
                0x8f_de_d9_ff,
                0xa2_e3_df_ff,
                0xb4_e9_e5_ff,
                0xc6_ee_eb_ff,
                0xd7_f3_f1_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0xf5_c2_e7_ff,
            fills: [
                0xf5_c2_e7_ff,
                0xf7_cd_eb_ff,
                0xf9_d8_f0_ff,
                0xfb_e3_f4_ff,
                0xfd_ee_f8_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0xcb_a6_f7_ff,
            fills: [
                0xcb_a6_f7_ff,
                0xd1_b0_f8_ff,
                0xd6_ba_fa_ff,
                0xdc_c4_fb_ff,
                0xe2_ce_fc_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0x84_8a_a5_ff,
            fills: [
                0x84_8a_a5_ff,
                0x8d_92_ac_ff,
                0x95_9b_b2_ff,
                0x9e_a3_b8_ff,
                0xa7_ab_bf_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0xf9_e2_af_ff,
            fills: [
                0xf9_e2_af_ff,
                0xfb_e9_c3_ff,
                0xfc_f0_d7_ff,
                0xfe_f8_eb_ff,
                0xff_ff_ff_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
        CategoryColors {
            accent: 0x93_99_b2_ff,
            fills: [
                0x93_99_b2_ff,
                0x9c_a1_b8_ff,
                0xa5_aa_bf_ff,
                0xae_b3_c6_ff,
                0xb8_bc_cd_ff,
            ],
            text: Some(0x11_11_1b_ff),
        },
    ],
    age: Age {
        swatches: [
            0x74_c7_ec_ff,
            0x81_b9_da_ff,
            0x89_ae_cc_ff,
            0x8e_a3_bf_ff,
            0x93_99_b2_ff,
        ],
        fills: [
            [
                0x74_c7_ec_ff,
                0x86_ce_ee_ff,
                0x98_d5_f1_ff,
                0xa9_dc_f4_ff,
                0xba_e2_f6_ff,
            ],
            [
                0x81_b9_da_ff,
                0x8f_c0_de_ff,
                0x9c_c8_e2_ff,
                0xaa_cf_e6_ff,
                0xb7_d7_ea_ff,
            ],
            [
                0x89_ae_cc_ff,
                0x94_b6_d1_ff,
                0xa0_be_d6_ff,
                0xab_c6_db_ff,
                0xb7_ce_e0_ff,
            ],
            [
                0x8e_a3_bf_ff,
                0x98_ab_c5_ff,
                0xa2_b3_cb_ff,
                0xac_bb_d0_ff,
                0xb6_c3_d6_ff,
            ],
            [
                0x93_99_b2_ff,
                0x9c_a1_b8_ff,
                0xa5_aa_bf_ff,
                0xae_b3_c6_ff,
                0xb8_bc_cd_ff,
            ],
        ],
    },
};

static CATPPUCCIN_QUIET_SHAPE: Shape = Shape {
    tile_radius: 3,
    gap_top: 6,
    gap_deep: 2,
    strip: Strip::Left,
    strip_width: 3,
    sheen: 0,
};

static CATPPUCCIN_QUIET_LIGHT: Palette = Palette {
    name: "Latte",
    ui: Ui {
        background: 0xe6_e9_ef_ff,
        surface: 0xef_f1_f5_ff,
        sidebar: 0xef_f1_f5_ff,
        inset: 0xdc_e0_e8_ff,
        foreground: 0x4c_4f_69_ff,
        secondary: 0x5c_5f_77_ff,
        bright: 0x2c_2e_3e_ff,
        border: 0xbc_c0_cc_ff,
        divider: 0x4c_4f_69_24,
        fill: 0x4c_4f_69_0d,
        accent: 0x1e_66_f5_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xf3_54_22_ff,
        on_highlight: 0x11_11_1b_ff,
        danger: 0xd2_0f_39_ff,
        success: 0x40_a0_2b_ff,
        warning: 0xdf_8e_1d_ff,
        hatch: 0x4c_4f_69_29,
        hover: 0x4c_4f_69_99,
        label: 0x4c_4f_69_ff,
        label_dim: 0x6c_6f_85_ff,
        meter_track: 0x4c_4f_69_1a,
        meter_used: 0x4c_4f_69_4d,
        marked_fill: 0xf0_cc_ce_ff,
        marked_outline: 0xd2_0f_39_ff,
        marked_text: 0xd2_0f_39_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x1e_66_f5_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xdc_8a_78_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x40_a0_2b_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x17_92_99_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xea_76_cb_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x88_39_ef_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x84_8e_bd_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xdf_8e_1d_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x9c_a0_b0_ff,
            fills: [
                0xef_f1_f5_ff,
                0xe7_e9_ef_ff,
                0xdf_e2_e8_ff,
                0xd8_da_e2_ff,
                0xd0_d3_dc_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x1e_66_f5_ff,
            0x49_7c_e2_ff,
            0x68_8b_d2_ff,
            0x83_96_c1_ff,
            0x9c_a0_b0_ff,
        ],
        fills: [
            [
                0xd6_e2_f7_ff,
                0xcc_db_f8_ff,
                0xc0_d4_f9_ff,
                0xb5_cd_f9_ff,
                0xaa_c6_fa_ff,
            ],
            [
                0xd8_e2_f4_ff,
                0xce_db_f3_ff,
                0xc3_d4_f3_ff,
                0xb9_cd_f2_ff,
                0xaf_c6_f1_ff,
            ],
            [
                0xdc_e3_f1_ff,
                0xd2_dc_ef_ff,
                0xc8_d4_ed_ff,
                0xbe_cd_ea_ff,
                0xb4_c6_e8_ff,
            ],
            [
                0xe0_e4_ee_ff,
                0xd6_dd_ea_ff,
                0xcd_d5_e6_ff,
                0xc4_cd_e1_ff,
                0xba_c5_dd_ff,
            ],
            [
                0xe3_e5_eb_ff,
                0xdb_dd_e4_ff,
                0xd2_d5_dd_ff,
                0xcb_cd_d7_ff,
                0xc2_c5_d0_ff,
            ],
        ],
    },
};

static CATPPUCCIN_QUIET_FRAPPE: Palette = Palette {
    name: "Frapp\u{e9}",
    ui: Ui {
        background: 0x29_2c_3c_ff,
        surface: 0x30_34_46_ff,
        sidebar: 0x30_34_46_ff,
        inset: 0x23_26_34_ff,
        foreground: 0xc6_d0_f5_ff,
        secondary: 0xa5_ad_ce_ff,
        bright: 0xe2_e7_fa_ff,
        border: 0x51_57_6d_ff,
        divider: 0xc6_d0_f5_1f,
        fill: 0xc6_d0_f5_0f,
        accent: 0x8c_aa_ee_ff,
        on_accent: 0x23_26_34_ff,
        highlight: 0xed_99_79_ff,
        on_highlight: 0x23_26_34_ff,
        danger: 0xe7_82_84_ff,
        success: 0xa6_d1_89_ff,
        warning: 0xe5_c8_90_ff,
        hatch: 0xc6_d0_f5_24,
        hover: 0xc6_d0_f5_99,
        label: 0xc6_d0_f5_ff,
        label_dim: 0xa5_ad_ce_ff,
        meter_track: 0xc6_d0_f5_1a,
        meter_used: 0xc6_d0_f5_4d,
        marked_fill: 0x5d_43_4d_ff,
        marked_outline: 0xe7_82_84_ff,
        marked_text: 0xe7_82_84_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x8c_aa_ee_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf2_d5_cf_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa6_d1_89_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x81_c8_be_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf4_b8_e4_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xca_9e_e6_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x88_90_ae_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xe5_c8_90_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x73_79_94_ff,
            fills: [
                0x30_34_46_ff,
                0x35_3a_4c_ff,
                0x3b_40_53_ff,
                0x41_46_5a_ff,
                0x47_4c_61_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x8c_aa_ee_ff,
            0x85_9b_d2_ff,
            0x7e_8f_bc_ff,
            0x79_84_a7_ff,
            0x73_79_94_ff,
        ],
        fills: [
            [
                0x38_3f_55_ff,
                0x3d_45_5e_ff,
                0x42_4b_67_ff,
                0x47_51_70_ff,
                0x4c_58_79_ff,
            ],
            [
                0x39_3e_54_ff,
                0x3e_45_5c_ff,
                0x43_4b_65_ff,
                0x48_51_6e_ff,
                0x4e_58_77_ff,
            ],
            [
                0x38_3e_52_ff,
                0x3e_44_5b_ff,
                0x43_4b_63_ff,
                0x49_51_6b_ff,
                0x4f_58_74_ff,
            ],
            [
                0x3a_3e_53_ff,
                0x3f_45_5a_ff,
                0x45_4b_62_ff,
                0x4b_51_6a_ff,
                0x51_58_71_ff,
            ],
            [
                0x39_3e_51_ff,
                0x3f_44_58_ff,
                0x46_4a_5f_ff,
                0x4c_51_67_ff,
                0x53_58_6e_ff,
            ],
        ],
    },
};

static CATPPUCCIN_QUIET_MACCHIATO: Palette = Palette {
    name: "Macchiato",
    ui: Ui {
        background: 0x1e_20_30_ff,
        surface: 0x24_27_3a_ff,
        sidebar: 0x24_27_3a_ff,
        inset: 0x18_19_26_ff,
        foreground: 0xca_d3_f5_ff,
        secondary: 0xa5_ad_cb_ff,
        bright: 0xe4_e9_fa_ff,
        border: 0x49_4d_64_ff,
        divider: 0xca_d3_f5_1f,
        fill: 0xca_d3_f5_0f,
        accent: 0x8a_ad_f4_ff,
        on_accent: 0x18_19_26_ff,
        highlight: 0xf3_a2_84_ff,
        on_highlight: 0x18_19_26_ff,
        danger: 0xed_87_96_ff,
        success: 0xa6_da_95_ff,
        warning: 0xee_d4_9f_ff,
        hatch: 0xca_d3_f5_24,
        hover: 0xca_d3_f5_99,
        label: 0xca_d3_f5_ff,
        label_dim: 0xa5_ad_cb_ff,
        meter_track: 0xca_d3_f5_1a,
        meter_used: 0xca_d3_f5_4d,
        marked_fill: 0x55_3a_48_ff,
        marked_outline: 0xed_87_96_ff,
        marked_text: 0xed_87_96_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x8a_ad_f4_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf6_e2_de_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa6_da_95_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x8a_d4_cb_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf5_bd_e6_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xc6_a0_f6_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x85_8c_aa_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xee_d4_9f_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x6e_73_8d_ff,
            fills: [
                0x24_27_3a_ff,
                0x29_2d_40_ff,
                0x2f_33_47_ff,
                0x35_39_4d_ff,
                0x3b_3f_54_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x8a_ad_f4_ff,
            0x82_9b_d4_ff,
            0x7b_8d_ba_ff,
            0x74_80_a3_ff,
            0x6e_73_8d_ff,
        ],
        fills: [
            [
                0x35_3d_58_ff,
                0x3a_43_61_ff,
                0x3f_4a_6a_ff,
                0x44_50_73_ff,
                0x49_57_7c_ff,
            ],
            [
                0x33_3a_53_ff,
                0x38_40_5b_ff,
                0x3e_46_64_ff,
                0x43_4d_6c_ff,
                0x49_54_76_ff,
            ],
            [
                0x32_38_4f_ff,
                0x38_3e_57_ff,
                0x3e_45_5f_ff,
                0x43_4b_68_ff,
                0x49_52_70_ff,
            ],
            [
                0x31_36_4b_ff,
                0x37_3c_52_ff,
                0x3c_42_5a_ff,
                0x42_49_62_ff,
                0x48_4f_6a_ff,
            ],
            [
                0x30_34_48_ff,
                0x36_3a_4f_ff,
                0x3c_40_56_ff,
                0x43_46_5d_ff,
                0x48_4d_63_ff,
            ],
        ],
    },
};

static CATPPUCCIN_QUIET_MOCHA: Palette = Palette {
    name: "Mocha",
    ui: Ui {
        background: 0x18_18_25_ff,
        surface: 0x1e_1e_2e_ff,
        sidebar: 0x1e_1e_2e_ff,
        inset: 0x11_11_1b_ff,
        foreground: 0xcd_d6_f4_ff,
        secondary: 0xa6_ad_c8_ff,
        bright: 0xe6_ea_fa_ff,
        border: 0x45_47_5a_ff,
        divider: 0xcd_d6_f4_1f,
        fill: 0xcd_d6_f4_0f,
        accent: 0x89_b4_fa_ff,
        on_accent: 0x11_11_1b_ff,
        highlight: 0xf9_ab_8f_ff,
        on_highlight: 0x11_11_1b_ff,
        danger: 0xf3_8b_a8_ff,
        success: 0xa6_e3_a1_ff,
        warning: 0xf9_e2_af_ff,
        hatch: 0xcd_d6_f4_24,
        hover: 0xcd_d6_f4_99,
        label: 0xcd_d6_f4_ff,
        label_dim: 0xa6_ad_c8_ff,
        meter_track: 0xcd_d6_f4_1a,
        meter_used: 0xcd_d6_f4_4d,
        marked_fill: 0x51_35_44_ff,
        marked_outline: 0xf3_8b_a8_ff,
        marked_text: 0xf3_8b_a8_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x89_b4_fa_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xfb_f3_f1_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa6_e3_a1_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x8f_de_d9_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf5_c2_e7_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xcb_a6_f7_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x84_8a_a5_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf9_e2_af_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x6c_70_86_ff,
            fills: [
                0x1e_1e_2e_ff,
                0x23_24_34_ff,
                0x29_2a_3a_ff,
                0x2f_2f_41_ff,
                0x34_35_47_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x89_b4_fa_ff,
            0x81_9f_d6_ff,
            0x7a_8e_b9_ff,
            0x73_7f_9f_ff,
            0x6c_70_86_ff,
        ],
        fills: [
            [
                0x30_36_4e_ff,
                0x34_3c_57_ff,
                0x39_42_5f_ff,
                0x3d_49_68_ff,
                0x42_4f_71_ff,
            ],
            [
                0x2e_33_49_ff,
                0x33_39_51_ff,
                0x38_3f_59_ff,
                0x3d_46_62_ff,
                0x43_4d_6b_ff,
            ],
            [
                0x2d_30_44_ff,
                0x32_36_4c_ff,
                0x37_3c_54_ff,
                0x3c_43_5c_ff,
                0x42_49_64_ff,
            ],
            [
                0x2c_2e_41_ff,
                0x32_34_48_ff,
                0x37_3b_50_ff,
                0x3d_41_57_ff,
                0x43_48_5f_ff,
            ],
            [
                0x2b_2b_3d_ff,
                0x31_32_43_ff,
                0x37_38_4a_ff,
                0x3d_3e_51_ff,
                0x43_45_58_ff,
            ],
        ],
    },
};

static AQUA_SHAPE: Shape = Shape {
    tile_radius: 5,
    gap_top: 6,
    gap_deep: 2,
    strip: Strip::Top,
    strip_width: 2,
    sheen: 6,
};

static AQUA_LIGHT: Palette = Palette {
    name: "Light",
    ui: Ui {
        background: 0xec_ec_ec_ff,
        surface: 0xff_ff_ff_ff,
        sidebar: 0xf0_f0_f0_c7,
        inset: 0xf7_f7_f8_ff,
        foreground: 0x00_00_00_d9,
        secondary: 0x5d_5d_62_ff,
        bright: 0x00_00_00_ff,
        border: 0xd5_d5_d8_ff,
        divider: 0x00_00_00_1a,
        fill: 0x00_00_00_0d,
        accent: 0x00_70_ec_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xff_95_00_ff,
        on_highlight: 0x1c_1c_1e_ff,
        danger: 0xff_3b_30_ff,
        success: 0x34_c7_59_ff,
        warning: 0xff_95_00_ff,
        hatch: 0x00_00_00_2b,
        hover: 0x00_00_00_80,
        label: 0x00_00_00_d6,
        label_dim: 0x00_00_00_85,
        meter_track: 0x00_00_00_14,
        meter_used: 0x00_00_00_4d,
        marked_fill: 0xff_cd_c5_ff,
        marked_outline: 0xff_3b_30_ff,
        marked_text: 0xb3_25_1c_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x00_7a_ff_ff,
            fills: [
                0xdf_ec_ff_ff,
                0xd2_e5_ff_ff,
                0xc5_dd_ff_ff,
                0xb7_d5_ff_ff,
                0xae_cd_f9_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xaf_52_de_ff,
            fills: [
                0xf4_e4_ff_ff,
                0xf0_d9_ff_ff,
                0xeb_ce_fd_ff,
                0xe2_c6_f4_ff,
                0xda_be_ec_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x34_c7_59_ff,
            fills: [
                0xcd_f9_d1_ff,
                0xc5_f0_c9_ff,
                0xbd_e8_c1_ff,
                0xb5_e0_b9_ff,
                0xad_d8_b1_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x30_b0_c7_ff,
            fills: [
                0xc6_f5_ff_ff,
                0xad_f0_ff_ff,
                0xa4_e8_f6_ff,
                0x9c_df_ee_ff,
                0x94_d7_e6_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xfa_2d_7f_ff,
            fills: [
                0xff_e3_e9_ff,
                0xff_d7_df_ff,
                0xff_cb_d6_ff,
                0xfb_c0_cd_ff,
                0xf3_b8_c5_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x58_56_d6_ff,
            fills: [
                0xe6_ea_ff_ff,
                0xdc_e1_ff_ff,
                0xd2_d8_ff_ff,
                0xc8_cf_ff_ff,
                0xc0_c7_f8_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x8e_8e_93_ff,
            fills: [
                0xe5_ec_f3_ff,
                0xdd_e4_eb_ff,
                0xd5_db_e3_ff,
                0xcd_d3_da_ff,
                0xc5_cb_d2_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xff_cc_00_ff,
            fills: [
                0xff_ea_b0_ff,
                0xf9_e1_a2_ff,
                0xf0_d9_9a_ff,
                0xe8_d1_92_ff,
                0xe0_c9_8a_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xae_ae_b2_ff,
            fills: [
                0xe9_eb_ee_ff,
                0xe1_e3_e5_ff,
                0xd9_db_dd_ff,
                0xd1_d3_d5_ff,
                0xc8_cb_cd_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x2e_78_dc_ff,
            0x56_87_cd_ff,
            0x73_94_c3_ff,
            0x8f_a0_b8_ff,
            0xab_ab_ab_ff,
        ],
        fills: [
            [
                0xba_d6_ff_ff,
                0xad_ce_ff_ff,
                0x9f_c6_ff_ff,
                0x93_be_fc_ff,
                0x8c_b6_f4_ff,
            ],
            [
                0xc3_dc_ff_ff,
                0xb6_d4_ff_ff,
                0xab_cc_fb_ff,
                0xa3_c4_f2_ff,
                0x9c_bc_ea_ff,
            ],
            [
                0xcd_e1_ff_ff,
                0xc3_d9_f9_ff,
                0xbb_d1_f1_ff,
                0xb3_c9_e8_ff,
                0xab_c1_e0_ff,
            ],
            [
                0xdb_e6_f6_ff,
                0xd3_de_ee_ff,
                0xcb_d6_e6_ff,
                0xc3_ce_dd_ff,
                0xbb_c6_d5_ff,
            ],
            [
                0xeb_eb_eb_ff,
                0xe3_e3_e3_ff,
                0xda_da_da_ff,
                0xd2_d2_d2_ff,
                0xca_ca_ca_ff,
            ],
        ],
    },
};

static AQUA_DARK: Palette = Palette {
    name: "Dark",
    ui: Ui {
        background: 0x2b_2b_2d_ff,
        surface: 0x32_32_34_ff,
        sidebar: 0x2e_2e_32_bd,
        inset: 0x1e_1e_20_ff,
        foreground: 0xff_ff_ff_d9,
        secondary: 0xa1_a1_a6_ff,
        bright: 0xff_ff_ff_ff,
        border: 0x48_48_4a_ff,
        divider: 0xff_ff_ff_1a,
        fill: 0xff_ff_ff_0f,
        accent: 0x00_72_e1_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xff_9f_0a_ff,
        on_highlight: 0x1c_1c_1e_ff,
        danger: 0xff_45_3a_ff,
        success: 0x30_d1_58_ff,
        warning: 0xff_9f_0a_ff,
        hatch: 0xff_ff_ff_2b,
        hover: 0xff_ff_ff_99,
        label: 0xff_ff_ff_ff,
        label_dim: 0xff_ff_ff_8c,
        meter_track: 0xff_ff_ff_17,
        meter_used: 0xff_ff_ff_52,
        marked_fill: 0x75_17_12_ff,
        marked_outline: 0xff_45_3a_ff,
        marked_text: 0xff_b3_ad_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x0a_84_ff_ff,
            fills: [
                0x16_38_63_ff,
                0x1e_40_6c_ff,
                0x26_48_75_ff,
                0x2e_51_7e_ff,
                0x36_59_87_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xbf_5a_f2_ff,
            fills: [
                0x47_29_57_ff,
                0x4f_31_60_ff,
                0x57_39_68_ff,
                0x60_41_71_ff,
                0x68_49_7a_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x30_d1_58_ff,
            fills: [
                0x12_43_1b_ff,
                0x1b_4b_23_ff,
                0x24_54_2b_ff,
                0x2c_5c_33_ff,
                0x35_65_3b_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x40_c8_e0_ff,
            fills: [
                0x00_40_4a_ff,
                0x00_48_53_ff,
                0x00_51_5d_ff,
                0x00_5a_68_ff,
                0x00_63_72_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xf9_38_86_ff,
            fills: [
                0x5a_22_34_ff,
                0x63_2a_3c_ff,
                0x6c_32_44_ff,
                0x75_3a_4c_ff,
                0x7e_42_54_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x5e_5c_e6_ff,
            fills: [
                0x2f_32_63_ff,
                0x36_3a_6c_ff,
                0x3e_42_75_ff,
                0x45_4a_7e_ff,
                0x4d_53_87_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x98_98_9d_ff,
            fills: [
                0x33_39_3e_ff,
                0x3b_40_46_ff,
                0x43_48_4e_ff,
                0x4b_50_56_ff,
                0x53_59_5f_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xff_d6_0a_ff,
            fills: [
                0x43_37_00_ff,
                0x4b_3f_0a_ff,
                0x54_47_14_ff,
                0x5c_4f_1d_ff,
                0x64_57_26_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x63_63_66_ff,
            fills: [
                0x36_38_3a_ff,
                0x3e_40_42_ff,
                0x46_48_4a_ff,
                0x4e_50_52_ff,
                0x56_58_5a_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x33_86_e9_ff,
            0x58_8e_d4_ff,
            0x71_95_c3_ff,
            0x88_9a_b1_ff,
            0x9e_9e_9e_ff,
        ],
        fills: [
            [
                0x0e_3f_78_ff,
                0x18_47_81_ff,
                0x21_50_8b_ff,
                0x29_58_94_ff,
                0x32_61_9d_ff,
            ],
            [
                0x1f_3e_67_ff,
                0x26_46_70_ff,
                0x2e_4f_79_ff,
                0x36_57_82_ff,
                0x3f_60_8b_ff,
            ],
            [
                0x2a_3d_56_ff,
                0x31_45_5e_ff,
                0x39_4d_67_ff,
                0x41_55_6f_ff,
                0x49_5e_78_ff,
            ],
            [
                0x31_3b_47_ff,
                0x39_42_4f_ff,
                0x41_4a_57_ff,
                0x49_53_60_ff,
                0x51_5b_68_ff,
            ],
            [
                0x38_38_38_ff,
                0x3f_3f_3f_ff,
                0x47_47_47_ff,
                0x50_50_50_ff,
                0x58_58_58_ff,
            ],
        ],
    },
};

static GRAPHITE_SHAPE: Shape = Shape {
    tile_radius: 3,
    gap_top: 4,
    gap_deep: 1,
    strip: Strip::Dot,
    strip_width: 6,
    sheen: 0,
};

static GRAPHITE_LIGHT: Palette = Palette {
    name: "Light",
    ui: Ui {
        background: 0xfa_fa_fa_ff,
        surface: 0xff_ff_ff_ff,
        sidebar: 0xff_ff_ff_ff,
        inset: 0xf4_f4_f5_ff,
        foreground: 0x27_27_2a_ff,
        secondary: 0x66_68_6f_ff,
        bright: 0x09_09_0b_ff,
        border: 0xe4_e4_e7_ff,
        divider: 0xec_ec_ef_ff,
        fill: 0xf0_f0_f2_ff,
        accent: 0x5e_6a_d2_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xf0_9c_17_ff,
        on_highlight: 0x1a_17_10_ff,
        danger: 0xe5_48_4d_ff,
        success: 0x30_a4_6c_ff,
        warning: 0xf0_9c_17_ff,
        hatch: 0x00_00_00_24,
        hover: 0x00_00_00_80,
        label: 0x1c_1c_1f_ff,
        label_dim: 0x1c_1c_1f_8f,
        meter_track: 0xe9_e9_ec_ff,
        meter_used: 0xa1_a1_aa_ff,
        marked_fill: 0xff_d1_cd_ff,
        marked_outline: 0xe5_48_4d_ff,
        marked_text: 0xb0_26_2b_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x53_81_c4_ff,
            fills: [
                0xe8_ed_f6_ff,
                0xdf_e5_ed_ff,
                0xd7_dd_e5_ff,
                0xcf_d5_dd_ff,
                0xc7_cd_d5_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x96_73_be_ff,
            fills: [
                0xef_eb_f4_ff,
                0xe6_e3_ec_ff,
                0xde_da_e3_ff,
                0xd6_d2_db_ff,
                0xce_ca_d3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x41_8d_55_ff,
            fills: [
                0xe7_ef_e8_ff,
                0xdf_e7_e0_ff,
                0xd7_df_d8_ff,
                0xcf_d7_d0_ff,
                0xc6_cf_c8_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x00_95_a1_ff,
            fills: [
                0xe3_f0_f1_ff,
                0xdb_e7_e9_ff,
                0xd3_df_e0_ff,
                0xcb_d7_d8_ff,
                0xc3_cf_d0_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xb8_64_87_ff,
            fills: [
                0xf5_e9_ed_ff,
                0xec_e1_e5_ff,
                0xe4_d9_dd_ff,
                0xdc_d1_d4_ff,
                0xd4_c9_cc_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xae_66_2f_ff,
            fills: [
                0xf4_eb_e5_ff,
                0xec_e2_dd_ff,
                0xe4_da_d4_ff,
                0xdb_d2_cc_ff,
                0xd3_ca_c4_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x73_74_77_ff,
            fills: [
                0xeb_ed_ef_ff,
                0xe3_e5_e7_ff,
                0xdb_dc_df_ff,
                0xd3_d4_d7_ff,
                0xcb_cc_cf_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x7f_72_28_ff,
            fills: [
                0xef_ed_e3_ff,
                0xe6_e5_db_ff,
                0xde_dd_d3_ff,
                0xd6_d5_cb_ff,
                0xce_cc_c3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa3_a5_a7_ff,
            fills: [
                0xed_ed_ed_ff,
                0xe4_e4_e4_ff,
                0xdc_dc_dc_ff,
                0xd4_d4_d4_ff,
                0xcc_cc_cc_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x59_64_cd_ff,
            0x68_74_bb_ff,
            0x77_80_ae_ff,
            0x86_8b_a2_ff,
            0x95_95_95_ff,
        ],
        fills: [
            [
                0xd4_dc_ff_ff,
                0xca_d3_ff_ff,
                0xbf_cb_ff_ff,
                0xb7_c2_f7_ff,
                0xaf_ba_ef_ff,
            ],
            [
                0xd9_e0_ff_ff,
                0xcf_d7_ff_ff,
                0xc7_cf_f6_ff,
                0xbf_c7_ee_ff,
                0xb7_bf_e6_ff,
            ],
            [
                0xde_e4_fe_ff,
                0xd6_dc_f5_ff,
                0xce_d4_ed_ff,
                0xc6_cc_e5_ff,
                0xbe_c4_dc_ff,
            ],
            [
                0xe6_e9_f6_ff,
                0xdd_e0_ed_ff,
                0xd5_d8_e5_ff,
                0xcd_d0_dd_ff,
                0xc5_c8_d5_ff,
            ],
            [
                0xed_ed_ed_ff,
                0xe5_e5_e5_ff,
                0xdd_dd_dd_ff,
                0xd4_d4_d4_ff,
                0xcc_cc_cc_ff,
            ],
        ],
    },
};

static GRAPHITE_DARK: Palette = Palette {
    name: "Dark",
    ui: Ui {
        background: 0x15_15_18_ff,
        surface: 0x1b_1b_1f_ff,
        sidebar: 0x1b_1b_1f_ff,
        inset: 0x0f_0f_12_ff,
        foreground: 0xd4_d4_d8_ff,
        secondary: 0x8f_90_98_ff,
        bright: 0xf4_f4_f5_ff,
        border: 0x2c_2c_33_ff,
        divider: 0x26_26_2c_ff,
        fill: 0x23_23_29_ff,
        accent: 0x5e_6a_d2_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xfc_aa_2b_ff,
        on_highlight: 0x14_14_14_ff,
        danger: 0xf2_55_5a_ff,
        success: 0x3d_d6_8c_ff,
        warning: 0xfc_aa_2b_ff,
        hatch: 0xff_ff_ff_26,
        hover: 0xff_ff_ff_8c,
        label: 0xec_ec_ee_ff,
        label_dim: 0xec_ec_ee_94,
        meter_track: 0x26_26_2c_ff,
        meter_used: 0x6b_6b_74_ff,
        marked_fill: 0x50_18_17_ff,
        marked_outline: 0xf2_55_5a_ff,
        marked_text: 0xff_b0_b3_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x77_a6_ec_ff,
            fills: [
                0x25_29_2f_ff,
                0x2c_31_37_ff,
                0x34_38_3f_ff,
                0x3c_40_47_ff,
                0x43_48_4f_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xbc_98_e5_ff,
            fills: [
                0x2a_27_2e_ff,
                0x32_2f_36_ff,
                0x39_36_3d_ff,
                0x41_3e_45_ff,
                0x49_46_4d_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x66_b2_78_ff,
            fills: [
                0x24_2b_25_ff,
                0x2c_32_2d_ff,
                0x33_3a_34_ff,
                0x3b_42_3c_ff,
                0x43_4a_44_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x2f_bc_ca_ff,
            fills: [
                0x22_2b_2c_ff,
                0x29_32_33_ff,
                0x30_3a_3b_ff,
                0x38_42_43_ff,
                0x40_4a_4b_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xe0_88_ab_ff,
            fills: [
                0x2e_26_29_ff,
                0x36_2e_31_ff,
                0x3e_35_38_ff,
                0x46_3d_40_ff,
                0x4e_45_48_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xd5_8a_55_ff,
            fills: [
                0x2e_27_23_ff,
                0x36_2f_2a_ff,
                0x3e_36_32_ff,
                0x45_3e_39_ff,
                0x4d_46_41_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x90_92_95_ff,
            fills: [
                0x28_29_2b_ff,
                0x2f_30_32_ff,
                0x37_38_3a_ff,
                0x3e_40_42_ff,
                0x46_48_4a_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xa3_97_4e_ff,
            fills: [
                0x2a_29_22_ff,
                0x32_31_29_ff,
                0x39_38_31_ff,
                0x41_40_38_ff,
                0x49_48_40_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x62_63_66_ff,
            fills: [
                0x29_29_29_ff,
                0x30_30_30_ff,
                0x38_38_38_ff,
                0x40_40_40_ff,
                0x48_48_48_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x83_93_ff_ff,
            0x8e_9c_e6_ff,
            0x98_a2_d1_ff,
            0xa1_a6_be_ff,
            0xab_ab_ab_ff,
        ],
        fills: [
            [
                0x24_29_53_ff,
                0x2b_31_5b_ff,
                0x32_39_64_ff,
                0x3a_41_6d_ff,
                0x41_49_76_ff,
            ],
            [
                0x25_2a_48_ff,
                0x2c_32_50_ff,
                0x34_39_59_ff,
                0x3b_41_61_ff,
                0x43_49_6a_ff,
            ],
            [
                0x26_2a_3d_ff,
                0x2e_32_45_ff,
                0x35_39_4d_ff,
                0x3d_41_55_ff,
                0x45_49_5e_ff,
            ],
            [
                0x28_2a_33_ff,
                0x2f_31_3b_ff,
                0x36_39_43_ff,
                0x3e_41_4b_ff,
                0x46_49_53_ff,
            ],
            [
                0x29_29_29_ff,
                0x30_30_30_ff,
                0x38_38_38_ff,
                0x40_40_40_ff,
                0x48_48_48_ff,
            ],
        ],
    },
};

static ROSE_PINE_SHAPE: Shape = Shape {
    tile_radius: 4,
    gap_top: 5,
    gap_deep: 2,
    strip: Strip::Left,
    strip_width: 3,
    sheen: 3,
};

static ROSE_PINE_LIGHT: Palette = Palette {
    name: "Dawn",
    ui: Ui {
        background: 0xfa_f4_ed_ff,
        surface: 0xff_fa_f3_ff,
        sidebar: 0xff_fa_f3_ff,
        inset: 0xf4_ed_e8_ff,
        foreground: 0x57_52_79_ff,
        secondary: 0x69_65_87_ff,
        bright: 0x4a_45_68_ff,
        border: 0xdf_da_d9_ff,
        divider: 0xf2_e9_e1_ff,
        fill: 0xf4_ed_e8_ff,
        accent: 0x81_6b_99_ff,
        on_accent: 0xff_ff_ff_ff,
        highlight: 0xea_9d_34_ff,
        on_highlight: 0x2a_27_40_ff,
        danger: 0xb5_44_6a_ff,
        success: 0x4a_92_5c_ff,
        warning: 0xea_9d_34_ff,
        hatch: 0x57_52_79_33,
        hover: 0x57_52_79_8c,
        label: 0x4a_45_68_ff,
        label_dim: 0x4a_45_68_bf,
        meter_track: 0xdf_da_d9_ff,
        meter_used: 0x98_93_a5_ff,
        marked_fill: 0xff_c6_d3_ff,
        marked_outline: 0xb5_44_6a_ff,
        marked_text: 0x9a_4a_63_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x28_69_83_ff,
            fills: [
                0xd3_f1_ff_ff,
                0xc9_ea_f9_ff,
                0xc2_e3_f2_ff,
                0xbb_db_eb_ff,
                0xb4_d4_e3_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x90_7a_a9_ff,
            fills: [
                0xf1_e6_ff_ff,
                0xea_de_fa_ff,
                0xe3_d6_f2_ff,
                0xdc_cf_eb_ff,
                0xd5_c8_e4_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x64_96_65_ff,
            fills: [
                0xdb_f3_db_ff,
                0xd4_eb_d4_ff,
                0xcd_e4_cd_ff,
                0xc6_dd_c6_ff,
                0xbf_d6_bf_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x56_94_9f_ff,
            fills: [
                0xce_f3_fa_ff,
                0xc6_ec_f3_ff,
                0xbf_e5_eb_ff,
                0xb8_dd_e4_ff,
                0xb1_d6_dd_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xd7_82_7e_ff,
            fills: [
                0xff_e4_e2_ff,
                0xfe_da_d8_ff,
                0xf6_d3_d0_ff,
                0xef_cc_c9_ff,
                0xe8_c5_c2_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x61_6c_ac_ff,
            fills: [
                0xe5_ea_ff_ff,
                0xdc_e2_ff_ff,
                0xd5_db_f8_ff,
                0xcd_d4_f1_ff,
                0xc6_cd_e9_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x71_70_78_ff,
            fills: [
                0xeb_ea_f3_ff,
                0xe4_e3_ec_ff,
                0xdc_db_e4_ff,
                0xd5_d4_dd_ff,
                0xce_cd_d6_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x98_7a_59_ff,
            fills: [
                0xff_e7_cc_ff,
                0xf8_df_c4_ff,
                0xf1_d8_bd_ff,
                0xe9_d1_b6_ff,
                0xe2_ca_af_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x98_93_a5_ff,
            fills: [
                0xec_ea_f0_ff,
                0xe4_e3_e9_ff,
                0xdd_dc_e1_ff,
                0xd6_d4_da_ff,
                0xcf_cd_d3_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0x92_6c_b9_ff,
            0x93_78_b2_ff,
            0x95_83_aa_ff,
            0x96_8e_a1_ff,
            0x99_97_9c_ff,
        ],
        fills: [
            [
                0xe5_d0_ff_ff,
                0xe0_c6_ff_ff,
                0xda_bf_f9_ff,
                0xd3_b8_f2_ff,
                0xcc_b1_ea_ff,
            ],
            [
                0xe8_d5_ff_ff,
                0xe2_cd_fb_ff,
                0xdb_c6_f3_ff,
                0xd4_bf_ec_ff,
                0xcc_b8_e4_ff,
            ],
            [
                0xea_dc_fc_ff,
                0xe3_d5_f4_ff,
                0xdc_ce_ed_ff,
                0xd4_c7_e6_ff,
                0xcd_bf_de_ff,
            ],
            [
                0xeb_e3_f5_ff,
                0xe4_dc_ee_ff,
                0xdc_d5_e6_ff,
                0xd5_ce_df_ff,
                0xce_c7_d8_ff,
            ],
            [
                0xec_ea_f0_ff,
                0xe5_e3_e8_ff,
                0xde_db_e1_ff,
                0xd7_d4_da_ff,
                0xd0_cd_d3_ff,
            ],
        ],
    },
};

static ROSE_PINE_DARK: Palette = Palette {
    name: "Moon",
    ui: Ui {
        background: 0x23_21_36_ff,
        surface: 0x2a_27_3f_ff,
        sidebar: 0x2a_27_3f_ff,
        inset: 0x1f_1d_2e_ff,
        foreground: 0xe0_de_f4_ff,
        secondary: 0x99_95_b3_ff,
        bright: 0xe0_de_f4_ff,
        border: 0x44_41_5a_ff,
        divider: 0x39_35_52_ff,
        fill: 0x2a_28_3e_ff,
        accent: 0xc4_a7_e7_ff,
        on_accent: 0x23_21_36_ff,
        highlight: 0xf6_c1_77_ff,
        on_highlight: 0x23_21_36_ff,
        danger: 0xe7_59_85_ff,
        success: 0x7c_cd_8e_ff,
        warning: 0xf6_c1_77_ff,
        hatch: 0xe0_de_f4_29,
        hover: 0xe0_de_f4_99,
        label: 0xe0_de_f4_ff,
        label_dim: 0xe0_de_f4_99,
        meter_track: 0x44_41_5a_ff,
        meter_used: 0x90_8c_aa_ff,
        marked_fill: 0x6f_1b_38_ff,
        marked_outline: 0xe7_59_85_ff,
        marked_text: 0xf7_b3_c6_ff,
    },
    categories: [
        CategoryColors {
            accent: 0x3e_8f_b0_ff,
            fills: [
                0x1c_3d_4a_ff,
                0x24_44_53_ff,
                0x2c_4d_5b_ff,
                0x34_55_63_ff,
                0x3d_5d_6c_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xc4_a7_e7_ff,
            fills: [
                0x3d_32_4b_ff,
                0x45_3a_53_ff,
                0x4d_42_5b_ff,
                0x55_4a_64_ff,
                0x5e_52_6d_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x7f_b8_80_ff,
            fills: [
                0x29_3e_29_ff,
                0x31_46_31_ff,
                0x38_4e_39_ff,
                0x40_57_40_ff,
                0x48_5f_49_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x9c_cf_d8_ff,
            fills: [
                0x17_3e_45_ff,
                0x20_46_4d_ff,
                0x28_4e_55_ff,
                0x30_57_5d_ff,
                0x39_5f_66_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xea_9a_97_ff,
            fills: [
                0x4d_2e_2d_ff,
                0x55_36_35_ff,
                0x5e_3e_3d_ff,
                0x66_46_45_ff,
                0x6f_4e_4d_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x80_8d_cf_ff,
            fills: [
                0x31_36_4f_ff,
                0x39_3e_58_ff,
                0x40_46_60_ff,
                0x48_4e_69_ff,
                0x50_56_72_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xb1_b0_b8_ff,
            fills: [
                0x38_37_3e_ff,
                0x40_3f_46_ff,
                0x47_47_4e_ff,
                0x50_4f_56_ff,
                0x58_57_5e_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0xb1_9a_7c_ff,
            fills: [
                0x46_34_1c_ff,
                0x4e_3c_24_ff,
                0x56_44_2c_ff,
                0x5f_4c_34_ff,
                0x67_55_3c_ff,
            ],
            text: None,
        },
        CategoryColors {
            accent: 0x6e_6a_86_ff,
            fills: [
                0x38_37_3c_ff,
                0x40_3f_44_ff,
                0x48_47_4c_ff,
                0x50_4f_54_ff,
                0x58_57_5c_ff,
            ],
            text: None,
        },
    ],
    age: Age {
        swatches: [
            0xc9_a3_f5_ff,
            0xbe_a3_df_ff,
            0xb3_a2_ca_ff,
            0xa9_a0_b4_ff,
            0x9f_9d_a2_ff,
        ],
        fills: [
            [
                0x4a_33_63_ff,
                0x52_3b_6c_ff,
                0x5b_43_75_ff,
                0x63_4b_7e_ff,
                0x6c_53_87_ff,
            ],
            [
                0x46_34_59_ff,
                0x4e_3c_62_ff,
                0x56_44_6a_ff,
                0x5e_4d_73_ff,
                0x67_55_7c_ff,
            ],
            [
                0x41_36_4f_ff,
                0x49_3e_57_ff,
                0x51_46_60_ff,
                0x5a_4e_68_ff,
                0x62_56_71_ff,
            ],
            [
                0x3d_37_44_ff,
                0x45_3e_4d_ff,
                0x4d_46_55_ff,
                0x55_4e_5d_ff,
                0x5d_57_66_ff,
            ],
            [
                0x39_37_3b_ff,
                0x41_3f_43_ff,
                0x48_47_4b_ff,
                0x51_4f_53_ff,
                0x59_57_5c_ff,
            ],
        ],
    },
};
